<a href="https://colab.research.google.com/github/sugban/OnePlus-Tution/blob/main/Python/Lesson7/Lesson_7_NumPy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
l1 = [1,2,3,4,5]
l2 = [[1,2,3,4,5],[6,7,8,9,10]]

In [ ]:
arr1 = np.array(l1)
print(arr1)

[1 2 3 4 5]


In [ ]:
arr2 = np.array(l2)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr1.ndim

1

In [ ]:
arr2.ndim

2

In [ ]:
arr1.shape

(5,)

In [ ]:
arr2.shape

(2, 5)

In [ ]:
arr2.size

10

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
array_A = np.array([1, 2, 3])
array_B = np.array([4, 5, 6])

print(array_A + array_B)

[5 7 9]


In [ ]:
months_array = np.array(['Jan', 'Feb', 'March', 'Apr', 'May'])
print(months_array[3])

Apr


In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

Yes   No
0   50  131
1   21    2

In [ ]:
pd.Series([12, 12, 33, 24, 15])

0    12
1    12
2    33
3    24
4    15
dtype: int64

In [ ]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

In [ ]:
data = [1,2,3,4,5]
df = pd.DataFrame(data)
df

0
0  1
1  2
2  3
3  4
4  5

In [ ]:
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
df

Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13

In [ ]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data)
df

Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42

In [ ]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
df

Name  Age
rank1    Tom   28
rank2   Jack   34
rank3  Steve   29
rank4  Ricky   42

In [ ]:
data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data, index=['first', 'second'])
df

a   b     c
first   1   2   NaN
second  5  10  20.0

In [ ]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
   'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [ ]:
print ("Adding a new column by passing as Series:")
df['three']=pd.Series([10,20,30],index=['a','b','c'])
df

Adding a new column by passing as Series:


one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN

In [ ]:
print ("Adding a new column using the existing columns in DataFrame:")
df['four']=df['one']+df['three']
df

Adding a new column using the existing columns in DataFrame:


one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   20.0  22.0
c  3.0    3   30.0  33.0
d  NaN    4    NaN   NaN

In [ ]:
# using del function
print ("Deleting the first column using DEL function:")
del df['one']
df

Deleting the first column using DEL function:


two  three  four
a    1   10.0  11.0
b    2   20.0  22.0
c    3   30.0  33.0
d    4    NaN   NaN

In [ ]:
# using pop function
print ("Deleting another column using POP function:")
df.pop('two')
df

Deleting another column using POP function:


three  four
a   10.0  11.0
b   20.0  22.0
c   30.0  33.0
d    NaN   NaN

In [ ]:
#Rows can be selected by passing row label to a loc function
df.loc['b']

three    20.0
four     22.0
Name: b, dtype: float64

In [ ]:
#Rows can be selected by passing integer location to an iloc function
df.iloc[2]

three    30.0
four     33.0
Name: c, dtype: float64

In [ ]:
#Multiple rows and columns can be selected using (:) operator
df[2:4]

three  four
c   30.0  33.0
d    NaN   NaN

In [ ]:
'''Add new rows to a DataFrame using the append function. This function will append the rows at the end.'''

df = pd.DataFrame([[1, 2], [3, 4]], columns = ['a','b'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns = ['a','b'])
df = df.append(df2)
df

a  b
0  1  2
1  3  4
0  5  6
1  7  8

In [ ]:
# Drop rows with label 0
df = df.drop(0)
df

a  b
1  3  4
1  7  8

In [ ]:
df.axes

[Int64Index([1, 1], dtype='int64'), Index(['a', 'b'], dtype='object')]

In [ ]:
df.empty

False

In [ ]:
df.ndim

2

In [ ]:
df.size

4

In [ ]:
df.values

array([[3, 4],
       [7, 8]])

In [ ]:
df.columns

Index(['a', 'b'], dtype='object')

In [ ]:
#Create a series with 10 random numbers
df=pd.Series(np.random.randn(10))
df

0    0.015876
1    2.184543
2   -0.492918
3    1.917517
4   -0.204578
5   -0.334553
6   -0.811826
7   -0.626854
8    0.173837
9   -0.571308
dtype: float64

In [ ]:
df.tail()

5   -1.048841
6   -1.023891
7   -1.560562
8   -0.510954
9   -1.960414
dtype: float64

In [ ]:
df.head()

0   -1.638788
1   -0.723161
2    0.014894
3    0.003342
4    0.174154
dtype: float64

In [ ]:
# read the drinks dataset into a DataFrame
drinks = pd.read_csv('http://bit.ly/drinksbycountry', index_col='country')
drinks.head()

beer_servings  ...  continent
country                     ...           
Afghanistan              0  ...       Asia
Albania                 89  ...     Europe
Algeria                 25  ...     Africa
Andorra                245  ...     Europe
Angola                 217  ...     Africa

[5 rows x 5 columns]

In [ ]:
# loc accesses by label
drinks.loc['Angola', 'spirit_servings']

57

In [ ]:
# iloc accesses by position
drinks.iloc[4, 1]

57

In [ ]:
drinks.isnull().sum()

beer_servings                   0
spirit_servings                 0
wine_servings                   0
total_litres_of_pure_alcohol    0
continent                       0
dtype: int64

In [ ]:
drinks.info()

<class 'pandas.core.frame.DataFrame'>
Index: 193 entries, Afghanistan to Zimbabwe
Data columns (total 5 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   beer_servings                 193 non-null    int64  
 1   spirit_servings               193 non-null    int64  
 2   wine_servings                 193 non-null    int64  
 3   total_litres_of_pure_alcohol  193 non-null    float64
 4   continent                     193 non-null    object 
dtypes: float64(1), int64(3), object(1)
memory usage: 14.0+ KB


In [ ]:
drinks.shape

(193, 5)

In [ ]:
drinks.columns

Index(['beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='object')

In [ ]:
drinks.rename(columns={'total_litres_of_pure_alcohol':'pure_alcohol'}, inplace=True)

In [ ]:
drinks.columns

Index(['beer_servings', 'spirit_servings', 'wine_servings', 'pure_alcohol',
       'continent'],
      dtype='object')

In [ ]:
drinks.reset_index(inplace=True)

In [ ]:
drinks.rename(str.upper, axis='columns',inplace=True)
drinks

COUNTRY  BEER_SERVINGS  ...  PURE_ALCOHOL      CONTINENT
0    Afghanistan              0  ...           0.0           Asia
1        Albania             89  ...           4.9         Europe
2        Algeria             25  ...           0.7         Africa
3        Andorra            245  ...          12.4         Europe
4         Angola            217  ...           5.9         Africa
..           ...            ...  ...           ...            ...
188    Venezuela            333  ...           7.7  South America
189      Vietnam            111  ...           2.0           Asia
190        Yemen              6  ...           0.1           Asia
191       Zambia             32  ...           2.5         Africa
192     Zimbabwe             64  ...           4.7         Africa

[193 rows x 6 columns]

In [ ]:
df=drinks.groupby('CONTINENT')['BEER_SERVINGS','SPIRIT_SERVINGS','WINE_SERVINGS'].sum()
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.


BEER_SERVINGS  SPIRIT_SERVINGS  WINE_SERVINGS
CONTINENT                                                   
Africa                  3258              866            862
Asia                    1630             2677            399
Europe                  8720             5965           6400
North America           3345             3812            564
Oceania                 1435              935            570
South America           2101             1377            749

In [ ]:
df1=drinks.groupby('CONTINENT')['BEER_SERVINGS','SPIRIT_SERVINGS','WINE_SERVINGS'].count()
df1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  """Entry point for launching an IPython kernel.


BEER_SERVINGS  SPIRIT_SERVINGS  WINE_SERVINGS
CONTINENT                                                   
Africa                    53               53             53
Asia                      44               44             44
Europe                    45               45             45
North America             23               23             23
Oceania                   16               16             16
South America             12               12             12

In [ ]:
drinks.loc[::-1].reset_index(drop=True).head() # to take 

COUNTRY  BEER_SERVINGS  ...  PURE_ALCOHOL      CONTINENT
0   Zimbabwe             64  ...           4.7         Africa
1     Zambia             32  ...           2.5         Africa
2      Yemen              6  ...           0.1           Asia
3    Vietnam            111  ...           2.0           Asia
4  Venezuela            333  ...           7.7  South America

[5 rows x 6 columns]